# Generated by Django 5.1.4 on 2025-01-12 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('task_01', 'Quick Task'), ('task_02', 'Medium Task'), ('task_03', 'Long Task'), ('task_04', 'Very Long Task'), ('task_05', 'Extremely Long Task')], max_length=50, unique=True)),
                ('execution_time_multiplier', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('domain', models.URLField(blank=True, null=True)),
                ('url', models.URLField(unique=True)),
                ('description', models.TextField()),
                ('record_capicity', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')])),
            ],
        ),
        migrations.CreateModel(
            name='JobQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_time', models.FloatField(blank=True, null=True)),
                ('worker_type', models.CharField(blank=True, max_length=20, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.job')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.site')),
            ],
        ),
        migrations.CreateModel(
            name='UserRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.site')),
            ],
        ),
    ]
