# Generated by Django 5.1.4 on 2025-01-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='quota_limit',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='site',
            name='quota_usage',
            field=models.IntegerField(default=0),
        ),
    ]
