version: "3.8"

services:
  web:
    build: .
    container_name: vanderval_app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=vanderval.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - .:/app

  celery_worker:
    build: .
    container_name: celery_worker
    command: ./start-celery.sh
    environment:
      - DJANGO_SETTINGS_MODULE=vanderval.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
